[package]
name = "searched"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.7"
env_logger = "0.11.5"
log = "0.4.22"
lru = "0.12.5"
once_cell = "1.20.2"
reqwest = { version = "0.12.8", features = ["cookies", "gzip", "json"] }
scraper = { version = "0.20.0", default-features = false, features = ["atomic"] }
serde = { version = "1.0.213", features = ["derive"] }
sled = "0.34.7"
tantivy = { version = "0.22.0", default-features = false, features = [
  "zstd-compression",
  "mmap",
  "stopwords",
] }
tera = "1.20.0"
texting_robots = "0.2.2"
tokio = { version = "1.41.0", features = [
  "rt-multi-thread",
  "macros",
  "signal",
] }
url = "2.5.2"
serde_qs = "0.13.0"
mlua = { version = "0.9.9", features = ["lua54", "async", "macros", "serialize", "send"] }
axum-macros = "0.4.2"
piccolo = "0.3.3"
piccolo-util = "0.3.3"
serde_json = "1.0.132"
crossbeam-channel = "0.5.13"
#mlua = { version = "0.9.9", features = ["luau-jit", "vendored", "async", "macros", "serialize"] }

[profile.dev.package.'*']
opt-level = 3

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = false
strip = true
debug-assertions = false
