[package]
name = "searched"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
env_logger = "0.11.3"
log = "0.4.21"
reqwest = "0.12.4"
scraper = "0.19.0"
serde = { version = "1.0.203", features = ["derive"] }
sled = "0.34.7"
tantivy = { version = "0.22.0", default-features = false, features = ["zstd-compression", "mmap", "stopwords"] }
tera = "1.20.0"
tokio = { version = "1.38.0", features = ["rt-multi-thread", "macros", "signal"] }
url = "2.5.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = false
strip = true
debug-assertions = false
