[provider.duckduckgo]
name = "DuckDuckGo"
description = "A privacy-respecting search engine"
kinds = ["sear"]

[provider.google]
name = "Google"
description = "The most popular search engine"
kinds = ["sear"]

[provider.wiby]
engine = "json_engine"
name = "Wiby"
description = "blah blah"
kinds = ["sear"]
